"""salesType

Revision ID: 214cb0a30e2a
Revises: 577bcabdcfa6
Create Date: 2021-06-13 18:01:52.222255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '214cb0a30e2a'
down_revision = '577bcabdcfa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salesType',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salesType_name'), 'salesType', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salesType_name'), table_name='salesType')
    op.drop_table('salesType')
    # ### end Alembic commands ###
