"""add tax

Revision ID: 577bcabdcfa6
Revises: e8332dbb33ce
Create Date: 2021-06-13 16:58:52.635321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577bcabdcfa6'
down_revision = 'e8332dbb33ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('valor', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_valor'), 'tax', ['valor'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tax_valor'), table_name='tax')
    op.drop_table('tax')
    # ### end Alembic commands ###
