"""add column modules_id

Revision ID: 97c41170a436
Revises: 214cb0a30e2a
Create Date: 2021-06-15 20:30:32.260925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97c41170a436'
down_revision = '214cb0a30e2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_name'), 'modules', ['name'], unique=False)
    op.add_column('menu', sa.Column('modules_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'menu', 'modules', ['modules_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menu', type_='foreignkey')
    op.drop_column('menu', 'modules_id')
    op.drop_index(op.f('ix_modules_name'), table_name='modules')
    op.drop_table('modules')
    # ### end Alembic commands ###
